### ISSUE TITLE
There is no way to use LoadingContext globally

### ISSUE THREAD

**Issue by paul-mais** [victortrusov/react-router-loading#11]
I need to change LoadigContext globally, now I'm trying this code
```tsx
import { useContext, useEffect } from 'react';
import { Route, LoadingContext, Switch, } from "react-router-loading"
import { useIsFetching } from 'react-query'

const App = () => {
  const loadingContext = useContext(LoadingContext);
  const isFetching = useIsFetching()

  useEffect(() => {
    // handle loading state globally by external library
    if(isFetching) loadingContext.start()
    else loadingContext.done()
  }, [isFetching])


  return (
    <Switch>
      <Route loading path="/" component={HomePage} />
      <Route loading path="/user" component={UserPage} />
      <Route loading path="/developer/:id" component={SettingPage} />
    </Switch>
  )
}
```
So the LoadingContext is not available because provided in Switch component 
and I don't know any other ways to get LoadingContext globally

**Comment by victortrusov** [comment]
Thanks for sharing. I will probably add prop `isLoading` to `Switch` so you can affect LoadingContext externally from `App`

**Comment by victortrusov** [comment]
I've just posted a new release v0.4.0 (https://github.com/victortrusov/react-router-loading/releases/tag/v0.4.0), now you're able to pass `isLoading` prop to the Switch 🎉
