### ISSUE TITLE
Wildcard and fallback routes do not work

### ISSUE THREAD

**Issue by grwgreg** [victortrusov/react-router-loading#13]
This lib was a great help to me but I believe I found two bugs. In the below example, the expected behavior is to have the NotFoundPage component render any non matching path. Instead the router renders nothing. 
```
<Switch>
    <Route path="/page1" component={Page1} />
    <Route path="/page2" component={Page2} />
    ...
    <Route component={NotFoundPage} />
</Switch>
```

Bug 2: When using a wildcard path an error is thrown, "Error: Invariant failed: You should not use \<Route\> outside a \<Router\>".
```
<Switch>
    <Route path="/page1" component={Page1} />
    <Route path="/page2" component={Page2} />
    ...
    <Route path="*" component={NotFoundPage} />
</Switch>
```

I was able to fix the first bug by modifying findMatchingRoute (https://github.com/victortrusov/react-router-loading/blob/master/src/utils.js#L6) to force a match when there is no path attribute on a route but I'm unsure if that breaks anything else. I suspect a better fix would solve both problems at once.

**Comment by victortrusov** [comment]
Thank you very much, @grwgreg!
I indeed forget to use RouterContext from original Switch component for wildcard and fallback routes support.
I will fix it in a new version soon

**Comment by victortrusov** [comment]
I've just posted a new release v0.4.0 (https://github.com/victortrusov/react-router-loading/releases/tag/v0.4.0) that supports these react-router features 🎉
