### ISSUE TITLE
Could you please update for React 18

### ISSUE THREAD

**Issue by yongyut-nathalin** [victortrusov/react-router-loading#19]
Now I see for good library but I have a some problem with react 18, sure I read for requirement, could you save my day thank you.

**Comment by victortrusov** [comment]
I added peer dependency to React 18 in [0.4.2](https://github.com/victortrusov/react-router-loading/releases/tag/v0.4.2), but the library still doesn't support React Router 6 (that might be a problem for you instead of React 18). React Router 6 will be supported in the upcoming v1 of the library

**Comment by victortrusov** [comment]
@yongyut-nathalin I've added support for React Router 6 if it helps you
