### ISSUE TITLE
It's not possible to use preload attribute with Typescript.

### ISSUE THREAD

**Issue by paul-mais** [victortrusov/react-router-loading#8]

**Comment by victortrusov** [comment]
Thank you for your interest!

I added `Route` with `preload` prop to the package in version [1.1.0](https://www.npmjs.com/package/react-easy-preload?activeTab=readme), so now you can import it from this package instead of `react-router-dom`
```js
import { PreloadingSwitch, Route } from "react-easy-preload";
```
